In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
###Sentences
sent =['the glass of milk',
       'the glass of juice',
       'the cup of tea', 
       'I am a good boy',
       'I am a good developer',
       'understanding the meaning of words',
       'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understanding the meaning of words',
 'your videos are good']

In [4]:
##Define the vocabulary
voc_size = 10000

In [5]:
##One Hot Representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1883, 1875, 3483, 829],
 [1883, 1875, 3483, 1518],
 [1883, 8300, 3483, 6582],
 [5530, 228, 4151, 928, 925],
 [5530, 228, 4151, 928, 1524],
 [5356, 1883, 164, 3483, 2752],
 [4869, 6127, 7165, 928]]

In [6]:
# word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1883 1875 3483  829]
 [   0    0    0    0 1883 1875 3483 1518]
 [   0    0    0    0 1883 8300 3483 6582]
 [   0    0    0 5530  228 4151  928  925]
 [   0    0    0 5530  228 4151  928 1524]
 [   0    0    0 5356 1883  164 3483 2752]
 [   0    0    0    0 4869 6127 7165  928]]


In [9]:
##feature representation
dim=10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\installs\Anaconda\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 1883, 1875, 3483,  829])

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step


array([[[ 0.01398813,  0.04342167, -0.01799824,  0.0299911 ,
         -0.02713105, -0.02691349, -0.04182844, -0.01788978,
          0.01850123,  0.0004001 ],
        [ 0.01398813,  0.04342167, -0.01799824,  0.0299911 ,
         -0.02713105, -0.02691349, -0.04182844, -0.01788978,
          0.01850123,  0.0004001 ],
        [ 0.01398813,  0.04342167, -0.01799824,  0.0299911 ,
         -0.02713105, -0.02691349, -0.04182844, -0.01788978,
          0.01850123,  0.0004001 ],
        [ 0.01398813,  0.04342167, -0.01799824,  0.0299911 ,
         -0.02713105, -0.02691349, -0.04182844, -0.01788978,
          0.01850123,  0.0004001 ],
        [ 0.04846552,  0.04849246,  0.00335366, -0.03692447,
         -0.01873431, -0.04310254, -0.02402752,  0.01364757,
         -0.04825021,  0.03358707],
        [-0.01487232, -0.04254901, -0.04099352, -0.01092126,
          0.04661634, -0.03981037,  0.04207045, -0.0183607 ,
          0.00896881,  0.01462561],
        [-0.03467013,  0.02833494, -0.00965958, -0.0